name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v1
      # install NPM dependencies but SKIP Cypress binary installation
      # see https://on.cypress.io/installing-cypress#Environment-variables
      - uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
